services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${BD_USER}
      POSTGRES_PASSWORD: ${BD_PASSWORD}
      POSTGRES_DB: ${BD_POSTGRES}
    ports:
      - "127.0.0.1:${BD_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
# docker compose up -d
